# Generated by Django 5.2.3 on 2025-08-26 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_savedprediction_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('num_career_predictions', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='career_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedCareerPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_title', models.CharField(default='', max_length=200)),
                ('career_code', models.CharField(default='', help_text='SOC/O*NET code', max_length=20)),
                ('match_score', models.FloatField(default=0.0, help_text='Match score between 0 and 1')),
                ('recommended_level', models.CharField(default='Recommended', max_length=50)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_predictions', to='api.careersession')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='saved_career_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('student', 'session', 'career_code')},
            },
        ),
    ]
