# Generated by Django 5.2.3 on 2025-09-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='careersession',
            name='degree_program',
            field=models.CharField(default='', help_text='The degree program used for career prediction', max_length=200),
        ),
    ]
