# Generated by Django 5.2.3 on 2025-08-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedprediction',
            name='recommendation',
            field=models.CharField(default='', help_text="Recommendation level, e.g., 'Recommended'", max_length=100),
        ),
    ]
